ASSEMBLER6502	= acme
AS_FLAGS	= -v0 -Wtype-mismatch
RM		= rm

PROGS		= mca2.prg example.prg
SRCS		= mca2.a engine.a tail.a

all: $(PROGS)

mca2.prg: $(SRCS) _autogenerated.a
	$(ASSEMBLER6502) $(AS_FLAGS) --outfile mca2.prg --format cbm _autogenerated.a mca2.a engine.a tail.a

example.prg: $(SRCS) _example.a
	$(ASSEMBLER6502) $(AS_FLAGS) --outfile example.prg --format cbm _example.a mca2.a engine.a tail.a

_autogenerated.a: conv.py situations.py
	./conv.py situations.py > _autogenerated.a

_example.a: conv.py example.py
	./conv.py example.py > _example.a

clean:
	-$(RM) -f *.o *.tmp $(PROGS) *~ core
